version: '3'
services:
  java-srv:
    build: java-srv
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - "db:db"
    command: sh -c "/wait && mvn clean spring-boot:run"
    environment:
      - WAIT_HOSTS=db:8091
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=90
      - WAIT_HOST_CONNECT_TIMEOUT=30
  
  db_seed:
    image: couchbase
    command: /bin/sh -c "./workspace/configure.sh"
    volumes:
      - ./db:/workspace
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=maria
      - COUCHBASE_ADMINISTRATOR_PASSWORD=ee4bbc53b558
      - COUCHBASE_BUCKET=animal
      - COUCHBASE_BUCKET_PASSWORD=f245b655c9da

  db:
    image: couchbase
    ports:
      - 8091
